### ISSUE TITLE
braces are not converted correctly

### ISSUE THREAD

**Issue by asottile** [pybpc/f2format#5]
👋 I wrote [essentially the same thing](https://github.com/asottile/future-fstrings) and decided to run my testsuite against it, this test fails:

```python
def test_with_braces():
    assert f'hello {{ hi }}' == 'hello { hi }'
```

**Comment by JarryShaw** [comment]
Hi there 👋 thx for reporting! We're actively upgrading the BPC suite recently (checkout [`walrus`](/pybpc/walrus), its super cool~). We will get onto it soon.

btw, `f2format` was, to be honest, *inspired* from `future-fstrings` at the begining xD and we even tried to make  `f2format-codec` (though it never worked out 🤦)

**Comment by asottile** [comment]
why reinvent the wheel?

**Comment by gousaiyang** [comment]
I don't remember why we started to write our own version. Maybe we just thought this was interesting to try. Or maybe because we didn't understand how "registering codec" works. We read from somewhere that "registering codec" will do something irreversible to the system and it felt unsafe to us. (Now we know it's a `pth` hack.)

Your solution is elegant that users can run code with f-strings on Python<3.6 transparently after installing you package. At that time we didn't notice that you also have `future-fstrings-show` (convert code ahead of time instead of just in time, like in our project). We thought the codec solution converts code everytime a script starts, which could be a performance issue. Also a file can only have one "coding cookie". You can not use `coding: future_fstrings` and another codec converter (like `coding: future_walrus`) at the same time without creating a super project like `future-superbackport` to do them all. And if some one uses encoding other than UTF-8 (although not encouraged), `coding: future_fstrings` will replace the original coding cookie and break the code. Now we notice that `future-fstrings-show` can solve all of these problems.

I really appreciate your work and I think both of our solutions will be useful for some people wishing to use new language features but still make code compatible with older versions of Python. We've also done backport for [positional-only arguments](https://github.com/pybpc/poseur) and [assignment expressions](https://github.com/pybpc/walrus) syntax in Python 3.8. Our test and documentation in this repo is poorly organized, and we are doing some overhaul of all these projects during our spare time.

**Comment by pmp-p** [comment]
> why reinvent the wheel?

Same goes for the cars using the wheels : because yours cannot roll on same roads.  cf https://github.com/asottile/future-fstrings/issues/40

Thanks a lot to pypbc for offering debug f-strings support.

**Comment by pmp-p** [comment]
@gousaiyang  @JarryShaw,  please re-open the bug is not fixed.

**Comment by JarryShaw** [comment]
hi there @pmp-p 

Thx for endorsing the `f2format` project. We're currently under progress of overall renovation of the PyBPC suites and thus no release had been made. However, you may check out the `master` branch, the bug described should have been resolved.

I shall reopen this issue. Pls kindly revert your feedback if any ;)

**Comment by JarryShaw** [comment]
@pmp-p we just made a pre-release [v0.8.7rc2](https://github.com/pybpc/f2format/releases/tag/v0.8.7rc2) and also available on [PyPI](https://pypi.org/project/f2format/0.8.7rc2/). Pls kindly check out the release and feedback any issue or flaws to us ;)

**Comment by pmp-p** [comment]
looks good on the pre-release version 0.8.7rc2, which is obviously better than the "stable" one which has the bug
you should make rc2 the new stable a.s.a.p.

**Comment by asottile** [comment]
could you make a new issue to discuss this please, there's no way to unsubscribe from issues you create
